Section "InputClass"
        Identifier      "calibration"
        MatchProduct    "eGalax Inc. USB TouchController"
        Option  "Calibration"   "4109 -67 4032 29"
        Option  "SwapAxes"      "1"
EndSection
